# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://chtudo.github.io/
title: Ux Design Office
email: sherlock@cht.com.tw
author: Sherlock
description: > # "The Life is play and play."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/twudo
  - title: github
    url: https://github.com/chtudo/chtudo.github.io
 # - title: linkedin
 #   url: 
